In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Dense, Activation
import datetime
from sklearn.preprocessing import MinMaxScaler
import csv
from tensorflow.keras.models import load_model

In [14]:
#칼럼들
days = ['일요일','월요일','화요일','수요일','목요일','금요일','토요일']
month = [1,2,3,4,5,6,7,8,9,10,11,12]
train = []
time = ['05~06','06~07','07~08','08~09','09~10','10~11','11~12','12~13','13~14','14~15','15~16','16~17','17~18','18~19','19~20','20~21','21~22','22~23','23~24','24~05']

In [15]:
#역명 CSV 파일을 읽은 후 TRAIN List에 데이터 삽입
f = open('Dataset/train_name.csv','r')
csvReader = csv.reader(f)

for row in csvReader:
    train.append(row)
    
f.close()

In [16]:
data = pd.read_csv('Dataset/All_Data.csv',encoding='CP949')
data.head()

날짜  월   요일          역명  05~06  06~07  07~08  08~09  ...  17~18  18~19  19~20  20~21  21~22  22~23  23~24  24~05
0  2012-01-01  1  일요일   가락시장(340)     27    113    137    240  ...    498    485    359    329    318    303    179      3
1  2012-01-01  1  일요일     가락시장(8)     61    120    118    233  ...    400    336    246    237    281    264    144     56
2  2012-01-01  1  일요일  가산디지털단지(7)     81    218    244    415  ...   1926   1803   1273   1092   1079    633    243     18
3  2012-01-01  1  일요일     강남(222)   1314   1683   1462   1604  ...   7099   6353   5188   5067   5427   4508   2285      2
4  2012-01-01  1  일요일        강남구청    200    395    280    439  ...    949    752    643    775    945    614    285      9

[5 rows x 24 columns]

In [17]:
data_value = (data['역명'] == '강남(222)') & (data['요일'] == '목요일') & (data['월'] == 5)
data_result = data[data_value]
data_result

날짜  월   요일       역명  05~06  06~07  07~08  08~09  ...  17~18  18~19  19~20  20~21  21~22  22~23  23~24  24~05
32721   2012-05-03  5  목요일  강남(222)   1057   4540  13659  22466  ...  14937  24093  20037  12689  14091  14583   7039   1920
34583   2012-05-10  5  목요일  강남(222)   1079   4319  13459  22395  ...  14970  24752  20020  12202  13565  14997   6952   1998
36445   2012-05-17  5  목요일  강남(222)   1118   4315  13460  22643  ...  14979  24786  19353  11958  13775  14670   6705   2047
38307   2012-05-24  5  목요일  강남(222)   1073   4225  13012  22417  ...  15302  24637  19086  12225  13591  14400   6852   1993
40169   2012-05-31  5  목요일  강남(222)   1099   3645  12474  21014  ...  14487  22987  18543  11961  12684  14162   7036   1890
131231  2013-05-02  5  목요일  강남(222)    987   4495  13050  22086  ...  14857  25471  20322  13296  14617  15936   7128   1805
133156  2013-05-09  5  목요일  강남(222)   1049   4494  13226  22790  ...  15320  25465  19741  12128  14246  15699   7204   1892
135081  2013-05-16  5  목요일  강남(222)   1082   4711  13177  21810  ...  16446  27247  23809  15002  14763  16201  10045   3390
137006  2013-05-23  5  목요일  강남(222)   1071   4435  13182  22289  ...  15920  25603  19742  12560  13887  14125   7174   1953
138931  2013-05-30  5  목요일  강남(222)   1049   4125  12056  22525  ...  14563  25317  19894  12540  13517  15543   7612   1932
231331  2014-05-01  5  목요일  강남(222)    999   2880   5291   9467  ...  14488  16094  12235   9619  11452  11238   5124   1476
233256  2014-05-08  5  목요일  강남(222)   1031   4623  13146  21811  ...  14833  24616  19602  12404  12901  11916   4837   1112
235181  2014-05-15  5  목요일  강남(222)   1173   4419  12711  22638  ...  15877  25320  21124  12883  14844  15496   7169   2072
237106  2014-05-22  5  목요일  강남(222)   1157   4523  13046  22512  ...  15313  25141  20618  12489  14268  14146   7031   1939
239031  2014-05-29  5  목요일  강남(222)   1109   4325  12384  22074  ...  15446  24592  19577  12433  13520  14892   6951   2094
333356  2015-05-07  5  목요일  강남(222)   1124   4255  12734  21067  ...  15090  24026  19352  12508  13430  14334   6391   1488
335281  2015-05-14  5  목요일  강남(222)   1133   4200  12322  20816  ...  14743  24324  19919  12488  13482  14565   7111   1870
337206  2015-05-21  5  목요일  강남(222)   1114   3981  12476  21418  ...  15528  24748  19372  12281  14073  13875   6731   1800
339131  2015-05-28  5  목요일  강남(222)   1081   3996  12053  21325  ...  14628  23451  18901  12077  13414  14027   6525   1732
433456  2016-05-05  5  목요일  강남(222)   1395   2343   2406   3496  ...  10910  11308   9693   7654   8854   8609   4541    206
435381  2016-05-12  5  목요일  강남(222)   1017   3752  10853  20033  ...  13963  23786  18615  12176  13651  14322   6670   1807
437306  2016-05-19  5  목요일  강남(222)   1027   3691  10569  20510  ...  15260  24533  19470  11929  13480  13514   6273   1661
439231  2016-05-26  5  목요일  강남(222)   1004   3613  10228  19356  ...  13795  22717  18010  11145  12558  13447   6244   1635

[23 rows x 24 columns]

In [18]:
#데이터 전처리
scaler = MinMaxScaler(feature_range=(0,1))
#행렬 다시 설정
temp = data_result['08~09'].values.reshape(-1,1)
trade_count = scaler.fit_transform(temp)

C:\Users\kkag2\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [19]:
def create_dataset(signal_data, look_back=1):
    x_arr, y_arr = [], []
    for i in range(len(signal_data) - look_back):
        x_arr.append(signal_data[i:(i + look_back),0])
        y_arr.append(signal_data[i + look_back,0])
        
    x_arr = np.array(x_arr)
    x_arr = np.reshape(x_arr, (x_arr.shape[0], x_arr.shape[1],1))
    
    return x_arr,np.array(y_arr)

In [20]:
#데이터 분리
#훈련
train = trade_count[0:int(len(trade_count) * 0.5)]
#검증
val = trade_count[int(len(trade_count) * 0.5) : int (len(trade_count) * 0.75)]
#시험
test = trade_count[int(len(trade_count) * 0.75): -1]

print("훈련 Data \n", train)
print("검증 Data \n", val)
print("시험 Data \n", test)

훈련 Data 
 [[0.98320721]
 [0.97952731]
 [0.99238105]
 [0.98066757]
 [0.90795066]
 [0.96351197]
 [1.        ]
 [0.94920701]
 [0.97403338]
 [0.98626516]
 [0.30947445]]
검증 Data 
 [[0.94925884]
 [0.9921219 ]
 [0.98559138]
 [0.96289002]
 [0.91069763]
 [0.8976884 ]]
시험 Data 
 [[0.92888981]
 [0.92406966]
 [0.        ]
 [0.85710584]
 [0.88182855]]


In [21]:
x_train, y_train = create_dataset(train, 1)
x_val, y_val = create_dataset(val, 1)
x_test, y_test = create_dataset(test,1)

print("x_train : ",x_train, "y_train : ",y_train)
print("x_val : ",x_val, "y_val : ",y_val)
print("x_test : ",x_test, "y_test : ",y_test)

x_train :  [[[0.98320721]]

 [[0.97952731]]

 [[0.99238105]]

 [[0.98066757]]

 [[0.90795066]]

 [[0.96351197]]

 [[1.        ]]

 [[0.94920701]]

 [[0.97403338]]

 [[0.98626516]]] y_train :  [0.97952731 0.99238105 0.98066757 0.90795066 0.96351197 1.
 0.94920701 0.97403338 0.98626516 0.30947445]
x_val :  [[[0.94925884]]

 [[0.9921219 ]]

 [[0.98559138]]

 [[0.96289002]]

 [[0.91069763]]] y_val :  [0.9921219  0.98559138 0.96289002 0.91069763 0.8976884 ]
x_test :  [[[0.92888981]]

 [[0.92406966]]

 [[0.        ]]

 [[0.85710584]]] y_test :  [0.92406966 0.         0.85710584 0.88182855]


In [22]:
#학습 모델 구성
batch_size = 22
model = Sequential()

model.add(LSTM(50, return_sequences=True, input_shape=(1, 1)))

model.add(LSTM(64, return_sequences=False))

#output
model.add(Dense(1, activation='linear'))

#손실
model.compile(loss='mse', optimizer='adam')

model.summary()

model.fit(x_train, y_train, validation_data=(x_val, y_val), batch_size=batch_size, epochs=20)

model.save('result.h5')

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 1, 50)             10400     
_________________________________________________________________
lstm_3 (LSTM)                (None, 64)                29440     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 65        
Total params: 39,905
Trainable params: 39,905
Non-trainable params: 0
_________________________________________________________________
Train on 10 samples, validate on 5 samples
Epoch 1/20
10/10 [==============================] - 2s 182ms/sample - loss: 0.8544 - val_loss: 0.8878
Epoch 2/20
10/10 [==============================] - 0s 1ms/sample - loss: 0.8426 - val_loss: 0.8754
Epoch 3/20
10/10 [==============================] - 0s 2ms/sample - loss: 0.8307 - val_loss: 0.8630
Epoch 4/20
10/10 [==============================] - 0s 1m

In [23]:
#모델 사용
predictions = model.predict(x_test, batch_size)  
real_predictions = scaler.inverse_transform(predictions)  # 0~1의 값으로 정규화된 값을 원래의 크기로 되돌린다.  
print("predicted next 5 min trade count", real_predictions[-1])  # 예측한 건수를 출력한다.

predicted next 5 min trade count [6360.385]
